import { useEffect, useState } from 'react';
import { FaBell, FaCheck, FaCircleExclamation, FaEnvelope, FaRotate } from 'react-icons/fa6';
import { getNotificationStatus, listNotificationLogs } from '@/services/cms';

const labels = {
  appointment_created_hospital: 'New appointment → hospital',
  appointment_received_patient: 'Appointment received → patient',
  appointment_status_patient: 'Appointment status → patient',
  appointment_status_manual: 'Manual appointment email',
};

function formatDate(value) {
  if (!value) return '—';
  return new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));
}

export default function Communications() {
  const [status, setStatus] = useState(null);
  const [logs, setLogs] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const refresh = async () => {
    setLoading(true); setError('');
    try {
      const [nextStatus, nextLogs] = await Promise.all([getNotificationStatus(), listNotificationLogs()]);
      setStatus(nextStatus); setLogs(nextLogs);
    } catch (err) { setError(err.message || 'Unable to load communication status.'); }
    finally { setLoading(false); }
  };

  useEffect(() => { refresh(); }, []);

  return <section>
    <div className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
      <div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-[hsl(var(--primary))]">Patient communication</p><h2 className="mt-2 font-display text-5xl">Communications</h2><p className="mt-3 max-w-2xl text-sm text-muted-foreground">Monitor transactional email delivery and the communication events generated by the hospital system.</p></div>
      <button onClick={refresh} disabled={loading} className="inline-flex items-center justify-center gap-2 rounded-full border px-4 py-2 text-sm font-semibold disabled:opacity-50"><FaRotate className={loading ? 'animate-spin' : ''} /> Refresh</button>
    </div>
    {error && <div className="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
    <div className="grid gap-4 md:grid-cols-3">
      <div className="rounded-2xl border bg-card p-5"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[hsl(var(--secondary))]"><FaEnvelope /></span><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${status?.configured ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-800'}`}>{status?.configured ? 'Configured' : 'Not configured'}</span></div><h3 className="mt-5 font-bold">Email delivery</h3><p className="mt-1 text-sm text-muted-foreground">Resend transactional email provider.</p></div>
      <div className="rounded-2xl border bg-card p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[hsl(var(--secondary))]"><FaBell /></span><h3 className="mt-5 font-bold">From address</h3><p className="mt-1 break-all text-sm text-muted-foreground">{status?.fromEmail || 'Not configured'}</p></div>
      <div className="rounded-2xl border bg-card p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[hsl(var(--secondary))]"><FaCheck /></span><h3 className="mt-5 font-bold">Delivery mode</h3><p className="mt-1 text-sm text-muted-foreground">{status?.note || 'Loading…'}</p></div>
    </div>
    <div className="mt-7 rounded-2xl border bg-card">
      <div className="border-b p-5"><h3 className="font-bold">Recent notification events</h3><p className="mt-1 text-xs text-muted-foreground">Mock mode keeps the latest communication events locally on the backend process.</p></div>
      {loading ? <div className="p-10 text-center text-sm text-muted-foreground">Loading communication events…</div> : !logs.length ? <div className="p-10 text-center"><FaCircleExclamation className="mx-auto text-2xl text-muted-foreground" /><p className="mt-3 text-sm text-muted-foreground">No notification events have been recorded yet.</p></div> : <div className="divide-y">{logs.map((log) => <div key={log.id} className="grid gap-2 p-5 md:grid-cols-[1fr_1fr_auto] md:items-center"><div><strong className="text-sm">{labels[log.type] || log.type}</strong><p className="mt-1 text-xs text-muted-foreground">{log.recipient || 'No recipient'} · {formatDate(log.created_at)}</p></div><p className="text-sm text-muted-foreground">{log.message}</p><span className={`w-fit rounded-full px-2.5 py-1 text-xs font-bold ${log.status === 'sent' ? 'bg-emerald-100 text-emerald-700' : log.status === 'failed' ? 'bg-red-100 text-red-700' : 'bg-amber-100 text-amber-800'}`}>{log.status}</span></div>)}</div>}
    </div>
  </section>;
}
